name: my_gmr
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  http: ^1.2.1
  flutter_dotenv: ^5.0.2
  geolocator: ^12.0.0
  weather_icons: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_secure_storage: ^9.2.2
  permission_handler: ^11.3.1
  go_router: ^14.1.4
  o3d: ^3.1.0
  intl: ^0.17.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  image_picker: ^1.1.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo_png.png
    - assets/robot_design.png
    - assets/info_robot_id.png
    - assets/area.png
    - assets/grass/g_2.png
    - assets/grass/g_4.png
    - assets/grass/g_8.png
    - assets/grass/g_10.png
    - assets/perrito.jpg
    - assets/google_logo.png
    - .env
  fonts:
    - family: Normal
      fonts:
        - asset: fonts/Inconsolata/Inconsolata-Regular.ttf

    - family: Title
      fonts:
        - asset: fonts/Kalam/Kalam-Regular.ttf

    - family: Logo
      fonts:
        - asset: fonts/Aldrich/Aldrich-Regular.ttf
