name: my_gmr
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  firebase_auth: ^4.19.5
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  google_sign_in: ^5.0.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo_png.png
    - assets/robot_design.png
    - assets/info_robot_id.png
    - assets/area.png
    - assets/grass/g_2.png
    - assets/grass/g_4.png
    - assets/grass/g_8.png
    - assets/grass/g_10.png
  fonts:
    - family: Normal
      fonts:
        - asset: fonts/Inconsolata/Inconsolata-Regular.ttf

    - family: Title
      fonts:
        - asset: fonts/Kalam/Kalam-Regular.ttf

    - family: Logo
      fonts:
        - asset: fonts/Aldrich/Aldrich-Regular.ttf
