name: mygmr-env
channels:
  - defaults
dependencies:
  - python=3.9
  - pip=19.3.1
  - pip:
    - flask
    - flask-session
    - google-cloud-storage
    - google-cloud-sql
    - requests
    - gunicorn
    - firebase-admin
    - python-dotenv
    - sqlalchemy
    - pg8000
    - numpy
    - trimesh
    - opencv-python
    - plyfile