name: flask
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - flask
    - sqlalchemy
    - pg8000
    - cloud-sql-python-connector
    - python-dotenv
    - firebase-admin
    - flask-session